import { Project } from './types';

export function getSampleData(): Project[] {
  const now = new Date();
  const oneWeekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);

  const sampleProject: Project = {
    id: 'sample_victoria_house',
    name: 'Victoria House Assessment',
    address: '42 Victoria Street, London SW1H 0NW',
    city: 'London',
    propertyType: 'Office',
    size: 3500,
    yearBuilt: 1985,
    clientName: 'Blackstone Capital',
    clientCompany: 'Blackstone Real Estate Partners',
    status: 'Complete',
    createdAt: oneWeekAgo.toISOString(),
    updatedAt: now.toISOString(),
    inputs: {
      condition: {
        overallStructuralCondition: 'Good',
        roofCondition: 'Fair',
        facadeCondition: 'Good',
        foundationIssues: 'None',
        internalLayoutQuality: 'Fair',
        floorToCeilingHeight: 2.7,
        naturalLightAssessment: 'Good',
        currentFitOutCondition: 'Dated',
        lastMajorRefurbishment: 2008,
        estimatedRemainingLifespan: 35,
        deferredMaintenanceEstimate: 450000,
      },
      planning: {
        currentUseClass: 'E',
        conservationArea: false,
        listedBuilding: 'Not Listed',
        article4Direction: false,
        permittedDevelopmentRights: true,
        extensionPotential: 'Moderate',
        changeOfUseFeasibility: 'Achievable',
        additionalFloorsPotential: 2,
        recentPlanningApplications: 'None',
        planningRiskLevel: 'Low',
        estimatedPlanningTimeline: 6,
      },
      mep: {
        electricalSystemAge: 18,
        electricalCapacity: 'Upgrade Needed',
        distributionBoardCondition: 'Fair',
        hvacSystemType: 'Central',
        hvacCondition: 'Fair',
        heatingSource: 'Gas',
        coolingProvision: 'Full',
        plumbingCondition: 'Good',
        waterPressure: 'Adequate',
        numberOfLifts: 2,
        liftCondition: 'Fair',
        liftModernisationNeeded: true,
        fireAlarmSystem: 'Compliant',
        sprinklerSystem: 'Partial',
        compartmentalisationStatus: 'Compliant',
      },
      costs: {
        currentAnnualRent: 875000,
        currentOccupancyRate: 78,
        currentAnnualServiceCharge: 145000,
        currentAnnualOperatingCosts: 220000,
        currentPropertyValueEstimate: 14500000,
        lightRefurbishmentEstimate: 180,
        fullRefurbishmentEstimate: 420,
        extensionConversionCostEstimate: 580,
        comparableRentCurrentUse: 320,
        comparableRentAlternativeUse: 450,
        targetYield: 5.5,
        estimatedSaleValuePostWorks: 22000000,
      },
      esg: {
        currentEPCRating: 'D',
        targetEPCRating: 'B',
        energyUseIntensity: 185,
        carbonEmissionsCurrent: 42,
        renewableEnergyOnSite: 'None',
        greenBuildingCertification: 'None',
        targetCertification: 'BREEAM Excellent',
        meesCompliant: true,
        meesDeadlineRisk: 'Medium',
        epbdGegImplications: 'Minor',
        occupierWellbeingFeatures: ['Cycling Facilities', 'Showers'],
        accessibilityRating: 'Partial',
      },
    },
    results: {
      recommendation: 'Optimise',
      recommendationSummary: 'The Value-Add strategy presents a viable path forward with modifications. Consider risk mitigation measures and phased implementation to enhance returns.',
      recommendedScenario: 'B',
      scenarios: {
        A: {
          id: 'A',
          name: 'Status Quo',
          description: 'Minimal intervention - maintain current use with basic compliance works only.',
          capitalRequired: 580000,
          projectedAnnualIncome: 682500,
          netYield: 4.5,
          irr: 7.2,
          esgScore: 'D',
          riskRating: 'Low',
          complexityRating: 'Low',
          timeline: 6,
          paybackPeriod: 8.5,
          epcRatingAchieved: 'D',
          meesCompliant: true,
          planningComplexity: 'Low',
          deliveryRisk: 'Low',
        },
        B: {
          id: 'B',
          name: 'Value-Add',
          description: 'Moderate investment with full refurbishment, targeting modern standards and potential use change.',
          capitalRequired: 1920000,
          projectedAnnualIncome: 1064000,
          netYield: 6.5,
          irr: 12.8,
          esgScore: 'C',
          riskRating: 'Medium',
          complexityRating: 'Medium',
          timeline: 14,
          paybackPeriod: 6.2,
          epcRatingAchieved: 'C',
          meesCompliant: true,
          planningComplexity: 'Medium',
          deliveryRisk: 'Medium',
        },
        C: {
          id: 'C',
          name: 'Maximum Value',
          description: 'Significant investment for full transformation with premium positioning and ESG leadership.',
          capitalRequired: 3450000,
          projectedAnnualIncome: 1417500,
          netYield: 7.9,
          irr: 15.4,
          esgScore: 'A',
          riskRating: 'High',
          complexityRating: 'High',
          timeline: 22,
          paybackPeriod: 5.8,
          epcRatingAchieved: 'A',
          meesCompliant: true,
          planningComplexity: 'High',
          deliveryRisk: 'High',
        },
      },
      cashFlowData: [
        { year: 1, scenarioA: -100000, scenarioB: -1050000, scenarioC: -2400000 },
        { year: 2, scenarioA: 480000, scenarioB: -180000, scenarioC: -1350000 },
        { year: 3, scenarioA: 1060000, scenarioB: 690000, scenarioC: -300000 },
        { year: 4, scenarioA: 1640000, scenarioB: 1560000, scenarioC: 750000 },
        { year: 5, scenarioA: 2220000, scenarioB: 2430000, scenarioC: 1800000 },
        { year: 6, scenarioA: 2800000, scenarioB: 3300000, scenarioC: 2850000 },
        { year: 7, scenarioA: 3380000, scenarioB: 4170000, scenarioC: 3900000 },
        { year: 8, scenarioA: 3960000, scenarioB: 5040000, scenarioC: 4950000 },
        { year: 9, scenarioA: 4540000, scenarioB: 5910000, scenarioC: 6000000 },
        { year: 10, scenarioA: 5120000, scenarioB: 6780000, scenarioC: 7050000 },
      ],
      riskReturnData: [
        { scenario: 'A', risk: 2, irr: 7.2 },
        { scenario: 'B', risk: 5, irr: 12.8 },
        { scenario: 'C', risk: 8, irr: 15.4 },
      ],
      riskFlags: [
        {
          severity: 'medium',
          message: 'EPC rating D requires upgrade to meet future MEES requirements by 2027',
        },
        {
          severity: 'medium',
          message: 'Lift modernisation required - budget £150k-200k',
        },
        {
          severity: 'low',
          message: 'Electrical capacity upgrade needed for modern occupier requirements',
        },
        {
          severity: 'low',
          message: 'Deferred maintenance backlog of £450k identified',
        },
      ],
      generatedAt: now.toISOString(),
    },
  };

  return [sampleProject];
}
